name: ChessDNN
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - chess
  - numpy
  - tensorflow
  - zstandard
  - numba
prefix: /home/eapen/anaconda3/envs/ChessDNN

# TODO rename to neurofish